FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD jagadish.jar /opt/jagadish/
EXPOSE 8080
WORKDIR /opt/jagadish/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "jagadish.jar"]
